/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: m.daneshyab (https://sketchfab.com/m.daneshyab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kimber-1911-12b70050f764456fb4db69a37a96c505
Title: Kimber 1911
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const Kimber = (props) => {
  const { nodes, materials } = useGLTF('/models/kimber.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.063, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 0.031, 5.809]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['body_low_Body+Parts_0'].geometry}
              material={materials.BodyParts}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['grip_right_low_Slide+Grips_0'].geometry}
              material={materials.SlideGrips}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['mag_low_Mag+Bullet_0'].geometry}
              material={materials.MagBullet}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['bullet_low_Mag+Bullet_0'].geometry}
              material={materials.MagBullet}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes['slide_low_Slide+Grips_0'].geometry}
              material={materials.SlideGrips}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

export default Kimber

useGLTF.preload('/models/kimber.glb')
